"""add enhanced data models for scheduling system

Revision ID: 604ba2287408
Revises: 
Create Date: 2025-09-12 00:00:00.230141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604ba2287408'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_conditions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('schedule_pattern', sa.JSON(), nullable=True),
    sa.Column('override_dates', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('calories_per_unit', sa.Float(), nullable=True),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('average_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('preferred_brand', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('initiatives',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM', name='initiativefrequency'), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='initiativestatus'), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('preferred_start_time', sa.String(length=8), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'DESSERT', name='mealtype'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'SHOPPING', 'PREPPING', 'COOKING', 'SERVED', 'CANCELLED', name='mealstatus'), nullable=False),
    sa.Column('serves_count', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.DateTime(), nullable=True),
    sa.Column('prep_start_time', sa.DateTime(), nullable=True),
    sa.Column('cook_start_time', sa.DateTime(), nullable=True),
    sa.Column('serve_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_calories_per_serving', sa.Integer(), nullable=True),
    sa.Column('dietary_tags', sa.JSON(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_templates',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PERSONAL', 'WORK', 'HOME', 'CREATIVE', 'LEARNING', 'HEALTH', 'CUSTOM', name='templatecategory'), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('phases_template', sa.JSON(), nullable=True),
    sa.Column('tasks_template', sa.JSON(), nullable=True),
    sa.Column('events_template', sa.JSON(), nullable=True),
    sa.Column('execution_script', sa.Text(), nullable=True),
    sa.Column('default_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('parent_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reminder_type', sa.Enum('TASK_START', 'TASK_DUE', 'EVENT_START', 'EVENT_PREP', 'MEAL_PREP', 'CUSTOM', name='remindertype'), nullable=False),
    sa.Column('default_minutes_before', sa.Integer(), nullable=True),
    sa.Column('message_template', sa.String(length=1000), nullable=False),
    sa.Column('applies_to_tasks', sa.Boolean(), nullable=True),
    sa.Column('applies_to_events', sa.Boolean(), nullable=True),
    sa.Column('applies_to_meals', sa.Boolean(), nullable=True),
    sa.Column('condition_tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedules',
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('default_work_start', sa.String(length=8), nullable=True),
    sa.Column('default_work_end', sa.String(length=8), nullable=True),
    sa.Column('min_task_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dishes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dish_type', sa.Enum('MAIN', 'SIDE', 'APPETIZER', 'DESSERT', 'BEVERAGE', 'SAUCE', 'BREAD', name='dishtype'), nullable=False),
    sa.Column('difficulty', sa.Enum('VERY_EASY', 'EASY', 'MEDIUM', 'HARD', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=True),
    sa.Column('advance_prep_hours', sa.Integer(), nullable=True),
    sa.Column('advance_prep_description', sa.Text(), nullable=True),
    sa.Column('default_servings', sa.Integer(), nullable=True),
    sa.Column('calories_per_serving', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_per_serving', sa.Float(), nullable=True),
    sa.Column('dietary_tags', sa.JSON(), nullable=True),
    sa.Column('recipe_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prep_task_templates',
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours_before_serve', sa.Integer(), nullable=True),
    sa.Column('minutes_before_serve', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_attention', sa.Boolean(), nullable=True),
    sa.Column('weather_dependent', sa.Boolean(), nullable=True),
    sa.Column('equipment_required', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='projectpriority'), nullable=False),
    sa.Column('estimated_start_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('initiative_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_pools',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('pool_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('allocated_minutes', sa.Integer(), nullable=True),
    sa.Column('available_minutes', sa.Integer(), nullable=False),
    sa.Column('weather_conditions', sa.JSON(), nullable=True),
    sa.Column('context_tags', sa.JSON(), nullable=True),
    sa.Column('is_work_time', sa.Boolean(), nullable=True),
    sa.Column('is_flexible', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_dishes',
    sa.Column('meal_id', sa.String(length=36), nullable=False),
    sa.Column('dish_id', sa.String(length=36), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prep_completed', sa.Boolean(), nullable=True),
    sa.Column('cook_completed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_phases',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('estimated_start_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('depends_on_phase_ids', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_executions',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('execution_parameters', sa.JSON(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('reminder_type', sa.Enum('TASK_START', 'TASK_DUE', 'EVENT_START', 'EVENT_PREP', 'MEAL_PREP', 'CUSTOM', name='remindertype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('minutes_before', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', 'SNOOZED', name='reminderstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('snooze_count', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('meal_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=100), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('predecessor_id', sa.String(length=36), nullable=False),
    sa.Column('successor_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('lag_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_schedules',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('time_pool_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('scheduled_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('minutes_worked', sa.Integer(), nullable=True),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['time_pool_id'], ['time_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('event_type', sa.Enum('MEETING', 'APPOINTMENT', 'DEADLINE', 'PERSONAL', 'WORK', 'TRAVEL', 'MEAL', 'BREAK', 'EXERCISE', 'CUSTOM', name='eventtype'), nullable=True))
    op.add_column('events', sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='eventstatus'), nullable=True))
    op.add_column('events', sa.Column('allows_multitasking', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('buffer_before_minutes', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('buffer_after_minutes', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('is_moveable', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('min_notice_hours', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('events', sa.Column('meal_id', sa.String(length=36), nullable=True))
    op.add_column('events', sa.Column('attendees', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('required_resources', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('reminder_minutes_before', sa.JSON(), nullable=True))
    # SQLite doesn't support ALTER COLUMN type changes - commenting out
    # op.alter_column('events', 'description',
    #            existing_type=sa.VARCHAR(length=1000),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    op.create_foreign_key(None, 'events', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'events', 'meals', ['meal_id'], ['id'])
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=True))
    op.add_column('tasks', sa.Column('is_divisible', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('min_chunk_size', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('required_weather', sa.Enum('ANY', 'SUNNY', 'CLOUDY', 'RAINY', 'SNOWY', 'CLEAR', 'WINDY', name='weathercondition'), nullable=True))
    op.add_column('tasks', sa.Column('required_context', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('equipment_needed', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('depends_on_task_ids', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('blocks_task_ids', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('initiative_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('phase_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('meal_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('queue_position', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('auto_scheduled', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_pattern', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('last_completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('partial_completion_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('remaining_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_snoozed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    # SQLite doesn't support ALTER COLUMN type changes - commenting out
    # op.alter_column('tasks', 'description',
    #            existing_type=sa.VARCHAR(length=1000),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    # op.alter_column('tasks', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('ACTIVE', 'BLOCKED', 'COMPLETED', name='taskstatus'),
    #            existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'meals', ['meal_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'initiatives', ['initiative_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'project_phases', ['phase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('ACTIVE', 'BLOCKED', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('tasks', 'snoozed_until')
    op.drop_column('tasks', 'is_snoozed')
    op.drop_column('tasks', 'remaining_minutes')
    op.drop_column('tasks', 'partial_completion_minutes')
    op.drop_column('tasks', 'last_completed_at')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'recurrence_pattern')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'actual_cost')
    op.drop_column('tasks', 'estimated_cost')
    op.drop_column('tasks', 'auto_scheduled')
    op.drop_column('tasks', 'queue_position')
    op.drop_column('tasks', 'meal_id')
    op.drop_column('tasks', 'phase_id')
    op.drop_column('tasks', 'project_id')
    op.drop_column('tasks', 'initiative_id')
    op.drop_column('tasks', 'blocks_task_ids')
    op.drop_column('tasks', 'depends_on_task_ids')
    op.drop_column('tasks', 'equipment_needed')
    op.drop_column('tasks', 'required_context')
    op.drop_column('tasks', 'required_weather')
    op.drop_column('tasks', 'min_chunk_size')
    op.drop_column('tasks', 'is_divisible')
    op.drop_column('tasks', 'priority')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('events', 'reminder_minutes_before')
    op.drop_column('events', 'required_resources')
    op.drop_column('events', 'attendees')
    op.drop_column('events', 'meal_id')
    op.drop_column('events', 'project_id')
    op.drop_column('events', 'min_notice_hours')
    op.drop_column('events', 'is_moveable')
    op.drop_column('events', 'priority')
    op.drop_column('events', 'buffer_after_minutes')
    op.drop_column('events', 'buffer_before_minutes')
    op.drop_column('events', 'allows_multitasking')
    op.drop_column('events', 'status')
    op.drop_column('events', 'event_type')
    op.drop_table('task_schedules')
    op.drop_table('task_dependencies')
    op.drop_table('reminders')
    op.drop_table('template_executions')
    op.drop_table('project_phases')
    op.drop_table('meal_dishes')
    op.drop_table('time_pools')
    op.drop_table('projects')
    op.drop_table('prep_task_templates')
    op.drop_table('dishes')
    op.drop_table('schedules')
    op.drop_table('reminder_templates')
    op.drop_table('recipes')
    op.drop_table('project_templates')
    op.drop_table('meals')
    op.drop_table('initiatives')
    op.drop_table('ingredients')
    op.drop_table('context_conditions')
    # ### end Alembic commands ###
