"""add_weather_forecasts_table

Revision ID: 91b8da1d6f93
Revises: 09125aad8ac6
Create Date: 2025-09-12 15:55:19.445909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b8da1d6f93'
down_revision: Union[str, None] = '09125aad8ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temp_high', sa.Float(), nullable=True),
    sa.Column('temp_low', sa.Float(), nullable=True),
    sa.Column('temp_current', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('precipitation_inches', sa.Float(), nullable=True),
    sa.Column('precipitation_probability', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('weather_description', sa.String(length=255), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('visibility_miles', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_forecast_date'), 'weather_forecasts', ['forecast_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecasts_forecast_date'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###