"""add_missing_task_enhancements

Revision ID: ac8299650abe
Revises: 91b8da1d6f93
Create Date: 2025-09-12 17:52:51.365739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8299650abe'
down_revision: Union[str, None] = '91b8da1d6f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so skipping type changes
    # op.alter_column('events', 'description', ...)
    
    # Add the new task columns
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=True))
    op.add_column('tasks', sa.Column('is_divisible', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('min_chunk_size', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('required_weather', sa.Enum('ANY', 'SUNNY', 'CLOUDY', 'RAINY', 'SNOWY', 'CLEAR', 'WINDY', name='weathercondition'), nullable=True))
    op.add_column('tasks', sa.Column('required_context', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('equipment_needed', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('depends_on_task_ids', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('blocks_task_ids', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('initiative_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('phase_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('meal_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('queue_position', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('auto_scheduled', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_pattern', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(length=36), nullable=True))
    op.add_column('tasks', sa.Column('last_completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('partial_completion_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('remaining_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_snoozed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    
    # SQLite doesn't support ALTER COLUMN, so skipping type changes
    # op.alter_column('tasks', 'description', ...)
    # op.alter_column('tasks', 'status', ...)
    
    # Add foreign keys (but only if the target tables exist)
    try:
        op.create_foreign_key(None, 'tasks', 'project_phases', ['phase_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'tasks', 'meals', ['meal_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'tasks', 'initiatives', ['initiative_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('ACTIVE', 'BLOCKED', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('tasks', 'snoozed_until')
    op.drop_column('tasks', 'is_snoozed')
    op.drop_column('tasks', 'remaining_minutes')
    op.drop_column('tasks', 'partial_completion_minutes')
    op.drop_column('tasks', 'last_completed_at')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'recurrence_pattern')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'actual_cost')
    op.drop_column('tasks', 'estimated_cost')
    op.drop_column('tasks', 'auto_scheduled')
    op.drop_column('tasks', 'queue_position')
    op.drop_column('tasks', 'meal_id')
    op.drop_column('tasks', 'phase_id')
    op.drop_column('tasks', 'project_id')
    op.drop_column('tasks', 'initiative_id')
    op.drop_column('tasks', 'blocks_task_ids')
    op.drop_column('tasks', 'depends_on_task_ids')
    op.drop_column('tasks', 'equipment_needed')
    op.drop_column('tasks', 'required_context')
    op.drop_column('tasks', 'required_weather')
    op.drop_column('tasks', 'min_chunk_size')
    op.drop_column('tasks', 'is_divisible')
    op.drop_column('tasks', 'priority')
    op.add_column('events', sa.Column('meal_id', sa.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
