"""add event exceptions and series splits tables plus RRULE support

Revision ID: 7694f9c015c7
Revises: e5380ce294e7
Create Date: 2025-09-14 23:18:24.876163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7694f9c015c7'
down_revision: Union[str, None] = 'e5380ce294e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_exceptions',
    sa.Column('master_event_id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_rescheduled', sa.Boolean(), nullable=False),
    sa.Column('new_start', sa.DateTime(), nullable=True),
    sa.Column('new_end', sa.DateTime(), nullable=True),
    sa.Column('custom_title', sa.String(length=255), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('custom_location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_series_splits',
    sa.Column('original_event_id', sa.String(length=36), nullable=False),
    sa.Column('new_event_id', sa.String(length=36), nullable=False),
    sa.Column('split_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['new_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('events_backup')
    op.add_column('events', sa.Column('recurrence_rrule', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('recurrence_end', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('dtstart', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('dtend', sa.DateTime(), nullable=True))
    op.alter_column('initiatives', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('initiatives', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('initiatives', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('initiatives', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('initiatives', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('initiatives', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('initiatives', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('initiatives', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('initiatives', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('initiatives', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('events', 'dtend')
    op.drop_column('events', 'dtstart')
    op.drop_column('events', 'timezone')
    op.drop_column('events', 'recurrence_end')
    op.drop_column('events', 'recurrence_rrule')
    op.create_table('events_backup',
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('start_time', sa.NUMERIC(), nullable=True),
    sa.Column('end_time', sa.NUMERIC(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('event_type', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('is_blocking', sa.NUMERIC(), nullable=True),
    sa.Column('allows_multitasking', sa.NUMERIC(), nullable=True),
    sa.Column('buffer_before_minutes', sa.INTEGER(), nullable=True),
    sa.Column('buffer_after_minutes', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('is_moveable', sa.NUMERIC(), nullable=True),
    sa.Column('min_notice_hours', sa.INTEGER(), nullable=True),
    sa.Column('is_recurring', sa.NUMERIC(), nullable=True),
    sa.Column('recurrence_pattern', sa.NUMERIC(), nullable=True),
    sa.Column('recurrence_master_id', sa.TEXT(), nullable=True),
    sa.Column('is_recurrence_master', sa.NUMERIC(), nullable=True),
    sa.Column('is_recurrence_exception', sa.NUMERIC(), nullable=True),
    sa.Column('recurrence_instance_date', sa.NUMERIC(), nullable=True),
    sa.Column('recurrence_parent_id', sa.TEXT(), nullable=True),
    sa.Column('project_id', sa.TEXT(), nullable=True),
    sa.Column('attendees', sa.NUMERIC(), nullable=True),
    sa.Column('required_resources', sa.NUMERIC(), nullable=True),
    sa.Column('reminder_minutes_before', sa.NUMERIC(), nullable=True),
    sa.Column('notifications_enabled', sa.NUMERIC(), nullable=True),
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('updated_at', sa.NUMERIC(), nullable=True)
    )
    op.drop_table('event_series_splits')
    op.drop_table('event_exceptions')
    # ### end Alembic commands ###
